package main

type LoRAMetadata struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Template         string   `json:"template"`
	URL              string   `json:"url"`
	TriggerWord      string   `json:"trigger_word"`
	Keywords         []string `json:"keywords"`
	NegativeKeywords []string `json:"negative_keywords"`
}

func GetAllZImageLoRAs() []*LoRAMetadata {
	return []*LoRAMetadata{
		{
			ID:          "mecha_klein",
			Name:        "Mecha Klein",
			TriggerWord: "mecha",
			Template:    "mecha, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/new_mecha_klein4b.safetensors",
			Keywords:    []string{"mecha", "fun", "anime realistic", "detailed cartoon high def"},
			NegativeKeywords: []string{"organic", "natural", "human only", "realistic photo", "landscape", "painting", "fuzzy"},
		},
		{
			ID:          "anime_serenity",
			Name:        "Anime Serenity Real Life",
			TriggerWord: "SERENITY style",
			Template:    "SERENITY style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/anime_blend_real_life%20SERENITY%20style.safetensors",
			Keywords:    []string{"anime real life", "serenity style", "anime blend", "realistic anime", "semi-realistic", "anime portrait", "beautiful anime", "soft anime", "anime character", "anime girl", "anime boy", "serene anime"},
			NegativeKeywords: []string{"cartoon", "chibi", "simple", "abstract", "pixel art"},
		},
		{
			ID:          "colorful_pop_art",
			Name:        "Colorful Pop Art",
			TriggerWord: "colorful pop art",
			Template:    "colorful pop art, intense colorful illustration, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/colorful_pop_art_intense_colorful_illustrations_turbo-lora-MSch_Psych_01.safetensors",
			Keywords:    []string{"pop art", "colorful", "vibrant", "intense colors", "illustration", "bold colors", "graphic art", "warhol style", "comic pop", "retro pop", "bright illustration", "psychedelic", "vivid colors"},
			NegativeKeywords: []string{"muted", "monochrome", "grayscale", "realistic", "photograph"},
		},
		{
			ID:          "cosplay_realistic",
			Name:        "Cosplay Realistic",
			TriggerWord: "cosplay",
			Template:    "cosplay, realistic, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/coser-V3-cosplay-realistic.safetensors",
			Keywords:    []string{"cosplay", "costume", "cosplayer", "realistic cosplay", "anime cosplay", "costume design", "character costume", "professional cosplay", "detailed costume", "convention", "fantasy cosplay", "game cosplay"},
			NegativeKeywords: []string{"cartoon", "drawing", "2d art", "illustration", "sketch"},
		},
		{
			ID:          "inkwash",
			Name:        "Ink Wash Painting",
			TriggerWord: "ink wash",
			Template:    "ink wash painting, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/inkwash_ink_painting_paints_lora.safetensors",
			Keywords:    []string{"ink wash", "ink painting", "sumi-e", "chinese ink", "japanese ink", "brush stroke", "traditional ink", "watercolor ink", "asian art", "calligraphy style", "monochrome ink", "brush painting"},
			NegativeKeywords: []string{"digital", "3d render", "photograph", "colorful", "neon"},
		},
		{
			ID:          "knight_stylism",
			Name:        "Knight Stylism HD",
			TriggerWord: "knight stylism",
			Template:    "knight stylism, intense detail, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/intense_detail_knight_stylism_highfi_cartoon_animesish.safetensors",
			Keywords:    []string{"knight", "medieval", "armor", "fantasy knight", "warrior", "sword", "shield", "castle", "dragon slayer", "paladin", "intense detail", "epic fantasy", "battle armor", "crusader", "illustration"},
			NegativeKeywords: []string{"modern", "sci-fi", "futuristic", "casual", "simple"},
		},
		{
			ID:          "water_cartoon",
			Name:        "Water Cartoon Vintage",
			TriggerWord: "water cartoon",
			Template:    "water cartoon, old charming hand drawn, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/myloraEX2_watercartoon_anime_old_charming_handrawn.safetensors",
			Keywords:    []string{"vintage cartoon", "hand drawn", "classic animation", "old style", "watercolor cartoon", "charming", "nostalgic", "retro anime", "classic disney", "traditional animation", "storybook"},
			NegativeKeywords: []string{"modern", "3d", "digital", "realistic", "photograph"},
		},
		{
			ID:          "needle_felting",
			Name:        "Needle Felting Knit",
			TriggerWord: "needle felting",
			Template:    "needle felting style, knitting style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/needle_felting%20style_loonalone_knitting_style%20.safetensors",
			Keywords:    []string{"needle felting", "felted", "wool", "knitted", "yarn", "crafted", "handmade", "plush", "soft toy", "cozy", "textile art", "fiber art", "cute felt"},
			NegativeKeywords: []string{"digital", "realistic", "photograph", "hard edges", "metallic"},
		},
		{
			ID:          "neon_paint",
			Name:        "Neon Paint Style",
			TriggerWord: "neon paint",
			Template:    "neon paint style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/NeonPaintStyle_Z-Image_512.safetensors",
			Keywords:    []string{"neon", "glow", "fluorescent", "bright colors", "neon lights", "cyberpunk", "synthwave", "retrowave", "glowing", "vibrant", "electric colors", "blacklight", "uv reactive"},
			NegativeKeywords: []string{"muted", "pastel", "grayscale", "natural", "realistic"},
		},
		{
			ID:          "mecha_zimage",
			Name:        "Mecha Anime Detailed",
			TriggerWord: "mecha anime",
			Template:    "mecha anime, detailed, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/new_mecha_zit_V2_anime_detailed_realistic_cartoon.safetensors",
			Keywords:    []string{"mecha", "fun", "anime realistic", "detailed cartoon high def", "sci-fi anime", "power suit", "anime detailed realistic cartoon", "anime mech"},
			NegativeKeywords: []string{"organic", "natural", "realistic photo", "simple", "minimalist"},
		},
		{
			ID:          "nsfw_master",
			Name:        "NSFW Master",
			TriggerWord: "nsfw",
			Template:    "nsfw, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/NSFW_master_ZIT_000008766.safetensors",
			Keywords:    []string{"nsfw", "adult", "explicit", "mature content", "erotic", "sensual", "nude", "adult art"},
			NegativeKeywords: []string{"sfw", "family friendly", "cute", "cartoon", "child"},
		},
		{
			ID:          "orcs",
			Name:        "Orcs Fantasy",
			TriggerWord: "orc",
			Template:    "orc, fantasy, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/orcs_zimage__orc_lora.safetensors",
			Keywords:    []string{"orc", "ork", "green skin", "fantasy creature", "warcraft", "goblin", "troll", "barbaric", "tribal", "warrior orc", "fantasy beast", "monster", "brute"},
			NegativeKeywords: []string{"human", "elf", "realistic", "modern", "cute"},
		},
		{
			ID:          "smartphone_realistic",
			Name:        "Smartphone Realistic",
			TriggerWord: "smartphone photo",
			Template:    "smartphone photo, realistic, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/smartphone_realistic_real_life_real_pic.safetensors",
			Keywords:    []string{"smartphone", "mobile photo", "iphone", "android photo", "selfie", "casual photo", "candid", "real life", "authentic", "snapshot", "phone camera", "social media", "instagram style"},
			NegativeKeywords: []string{"professional", "studio", "dslr", "artistic", "painting"},
		},
		{
			ID:          "pixel_art",
			Name:        "Tartarus Pixel Art",
			TriggerWord: "pixel art",
			Template:    "pixel art, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/TartarusPixel_pixelart_pixels.safetensors",
			Keywords:    []string{"pixel art", "8bit", "16bit", "retro game", "sprite", "pixelated", "game asset", "indie game", "retro style", "classic game", "pixel graphics", "chiptune aesthetic"},
			NegativeKeywords: []string{"smooth", "high resolution", "realistic", "photograph", "3d"},
		},
		{
			ID:          "tshirt_comic",
			Name:        "T-Shirt Comic Design",
			TriggerWord: "tshirt design",
			Template:    "tshirt design, comic style, centered, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/tshirt_comic_pixelart_centered_lora_v1.safetensors",
			Keywords:    []string{"tshirt", "t-shirt design", "shirt graphic", "apparel design", "print design", "merchandise", "centered design", "logo design", "comic style", "graphic tee", "fashion graphic", "pixel comic art"},
			NegativeKeywords: []string{"landscape", "background heavy", "realistic photo", "complex scene"},
		},
		{
			ID:          "flat_anime",
			Name:        "Flat Anime Style",
			TriggerWord: "flat anime",
			Template:    "flat anime style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/UU_flat_anime_style_000000960.safetensors",
			Keywords:    []string{"flat anime", "cel shaded", "clean lines", "simple anime", "vector style", "solid colors", "minimalist anime", "modern anime", "crisp anime", "flat color", "anime illustration"},
			NegativeKeywords: []string{"realistic", "detailed shading", "3d", "photograph", "complex"},
		},
		{
			ID:          "watercolor_art",
			Name:        "Watercolor Art",
			TriggerWord: "watercolor",
			Template:    "watercolor art, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/watercolor-art-image-lora_v1_3000.safetensors",
			Keywords:    []string{"watercolor", "aquarelle", "wet paint", "soft edges", "flowing colors", "traditional art", "painting", "artistic", "brush strokes", "delicate", "transparent colors", "paper texture"},
			NegativeKeywords: []string{"digital", "sharp", "photograph", "3d render", "hard edges"},
		},
		{
			ID:          "z_art",
			Name:        "Z-Art Style",
			TriggerWord: "z-art",
			Template:    "z-art style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/Z-Art-3.safetensors",
			Keywords:    []string{"z-art", "artistic", "creative", "stylized", "unique style", "modern art", "digital art", "contemporary", "expressive", "abstract elements", "artistic interpretation"},
			NegativeKeywords: []string{"realistic", "photograph", "plain", "simple", "basic"},
		},
		{
			ID:          "aesthetic_base",
			Name:        "Aesthetic Base",
			TriggerWord: "aesthetic",
			Template:    "aesthetic, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/Z-Image-Aesthetic-Base%20v1.safetensors",
			Keywords:    []string{"aesthetic", "beautiful", "visually pleasing", "artistic", "harmonious", "balanced composition", "eye catching", "stylish", "trendy", "instagram aesthetic", "vaporwave"},
			NegativeKeywords: []string{"ugly", "messy", "chaotic", "low quality", "amateur"},
		},
		{
			ID:          "anime_epic_nsfw",
			Name:        "Anime Epic Stylized",
			TriggerWord: "epic anime",
			Template:    "epic stylized anime, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/z-image-anime-01-epic-stylized-nsfw.safetensors",
			Keywords:    []string{"epic anime", "stylized anime", "dramatic anime", "intense anime", "action anime", "dynamic anime", "powerful", "heroic anime", "anime art", "detailed anime", "impressive anime"},
			NegativeKeywords: []string{"simple", "minimal", "cute", "chibi", "slice of life", "kid", "realistic"},
		},
		{
			ID:          "anime_artistic",
			Name:        "Anime Artistic Interesting",
			TriggerWord: "artistic anime",
			Template:    "artistic anime, interesting style, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/Z-IMAGE_ANIME_ineresting_anime_artistic.safetensors",
			Keywords:    []string{"artistic anime", "creative anime", "unique anime", "interesting style", "experimental anime", "avant-garde anime", "stylish anime", "anime illustration", "anime concept art"},
			NegativeKeywords: []string{"basic", "generic", "simple", "standard", "boring"},
		},
		{
			ID:          "cosplay_nsfw",
			Name:        "Cosplay NSFW",
			TriggerWord: "cosplay nsfw",
			Template:    "cosplay, nsfw, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/zimage_cos-NSFW-lora.safetensors",
			Keywords:    []string{"cosplay nsfw", "sexy cosplay", "adult cosplay", "erotic costume", "mature cosplay", "risque costume", "provocative"},
			NegativeKeywords: []string{"sfw", "family friendly", "cartoon", "child", "innocent"},
		},
		{
			ID:          "samdoesarts",
			Name:        "Sam Does Arts Comic",
			TriggerWord: "samdoesarts style",
			Template:    "samdoesarts style, comic cartoon, {prompt}",
			URL:         "https://netwrckstatic.netwrck.com/static/loras/z-samdoesarts_style_comic_cartoon.safetensors",
			Keywords:    []string{"samdoesarts", "comic style", "cartoon", "stylized portrait", "digital painting", "character art", "illustration", "expressive", "bold lines", "vibrant"},
			NegativeKeywords: []string{"realistic", "photograph", "plain", "simple", "abstract"},
		},
	}
}
